import '@/styles/index.scss';
import 'react-data-grid/lib/styles.css';

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider, theme } from 'antd';
import viVN from 'antd/locale/vi_VN';
import HolyLoader from 'holy-loader';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <HolyLoader height="3px" easing="linear" showSpinner />
      <body>
        <AntdRegistry>
          <ConfigProvider
            locale={viVN}
            theme={{
              token: {
                fontFamily: 'Roboto, sans-serif',
              },
              algorithm: theme.defaultAlgorithm,
            }}
          >
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
